create table task (
    id bigint primary key generated by default as identity,
    id_chat bigint,
    notification varchar(256),
    date timestamp not null,
    unique (id_chat, notification, date)
);